[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "ansibulled"
version = "0.1.0"
description = "Tools for building the Ansible Distribution"
authors = ["Toshio Kuratomi <a.badger@gmail.com>"]
license = "GPL-3.0-or-later"
readme = "README.md"
repository = "https://github.com/ansible-community/ansibulled"
packages = [
    { include = "ansibulled" },
    { include = "tests", format = "sdist" }
]

[tool.poetry.scripts]
ansibulled = "ansibulled.cli.ansibulled:main"

[tool.poetry.dependencies]
python = "^3.5.3"
aiofiles = "^0.5.0"
aiohttp = "^3.6.2"
jinja2 = "^2.11.2"
packaging = "^20.3"
semantic_version = "^2.8.5"
sh = "^1.13.1"

[tool.poetry.dev-dependencies]
pytest-asyncio = "^0.11.0"
asynctest = "^0.13.0"
pytest = "^5.4.1"
pytest-cov = "^2.8.1"
